resources: [../../base]
images:
  - name: rollout-demo
    newName: 767866852518.dkr.ecr.us-east-1.amazonaws.com/rollout-demo
    digest: sha256:TROCAR # o mesmo digest que passou em dev
patches:
  - path: rollout.yaml
