apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: geral
spec:
  template:
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["5"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: geral
  limits:
    cpu: 32 # freio de custo
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: geral
spec:
  role: "Karpenter-lab-dev-3934b5f3b6de3025b383e6b519" # node_iam_role_name do terragrunt
  amiSelectorTerms:
    - alias: al2023@latest # lab; produção: versão fixa
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: lab-dev
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: lab-dev
